// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTSnHo5htLIrmjR228n2hud9_oWEtJW8',
    appId: '1:283648865832:web:2e7f83df8f4e44d22b271d',
    messagingSenderId: '283648865832',
    projectId: 'trsmartlamp',
    authDomain: 'trsmartlamp.firebaseapp.com',
    databaseURL: 'https://trsmartlamp-default-rtdb.firebaseio.com',
    storageBucket: 'trsmartlamp.appspot.com',
    measurementId: 'G-7BCXNF04GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnKLbGD6kVJmGA2zVNxlqJyZVcnlXbRiE',
    appId: '1:283648865832:android:38c1348899b985fb2b271d',
    messagingSenderId: '283648865832',
    projectId: 'trsmartlamp',
    databaseURL: 'https://trsmartlamp-default-rtdb.firebaseio.com',
    storageBucket: 'trsmartlamp.appspot.com',
  );
}
